# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

markdown: kramdown
timezone: Europe/Berlin
sass:
  style: compressed

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.saraheichner.de # the base hostname & protocol for your site
repository: lotterliebe/lotterliebe.github.io

# content settings
title: Sarah Eichner
subtitle: Texterin & Online-Redakteurin aus Berlin
email: mail@saraheichner.de
description: >
  Sarah Eichner - Texterin & Online-Redakteurin aus Berlin
keywords: Freie Texterin,Online-Redakteurin,Berlin,Redaktion,Lektorat,Texten,Schreiben,Korrektur,Autor,Bloggen,Berlin,Übersetzung

# profiles
twitter_username: lotterliebe
github_username: lotterliebe
xing_username: Sarah_Eichner
linkedin_username: sarahcurth
instagram_username: lotterliebe

# List of files & directories jekyll should not put into the _site directory
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile
  - MIT-LICENSE
  - Procfile
  - Rakefile
  - README.md
